using System;


namespace UserControl.Core.DTOs
{
    public class PostDto
    {
        //No puede tener ningun tipo de logica dentro de ellos
        //public int PostId { get; set; }

        /// <summary>
        /// Autogenerated id for post entity
        /// </summary>
        public int Id { get; set; }

        public int UserId { get; set; }

        public DateTime Date { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }
    }
}
